# Generated by Django 3.0.6 on 2021-10-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('user_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('user_password', models.CharField(blank=True, default=None, max_length=100)),
                ('user_image', models.ImageField(upload_to='uploads/')),
                ('user_phone', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True)),
                ('user_address', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
